live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
# decorations = "buttonless"
dynamic_padding = false
opacity = 0.9
title = "Das Terminal"

[window.padding]
x = 5
y = 0

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font Mono"
#style = "Medium"

[window.dimensions]
columns = 100
lines = 40

[shell]
program = "/bin/bash"
args = ["-l"]
