#!/bin/bash -eu

test -d ~/.zsh/fzf-tab || \
    git clone https://github.com/Aloxaf/fzf-tab ~/.zsh/fzf-tab

test -d ~/.zsh/zsh-autosuggestions || \
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions

